#!/usr/bin/env bash
# debug.sh — Launch Factorio headless with creative-mod for debugging
#
# Usage:
#   ./debug.sh           — start headless server (blocks; Ctrl-C to stop)
#   ./debug.sh reset     — delete the debug save and recreate it
#   ./debug.sh log       — tail the game log (while server is running)
#   ./debug.sh console   — tail the console log (game.print output)
#
# Output channels:
#   .debug/factorio-current.log  — all Lua errors, log() calls, engine messages
#   .debug/factorio-current.log  — Lua log() calls and engine messages
#   .debug/console.log           — raw server console (commands, warnings)
#   .debug/script-output/        — game.write_file() output
#
# After the server is up, use rcon.sh or rcon.py to send commands:
#   ./rcon.sh '/c rcon.print(game.tick)'         — inspect value (echoed back)
#   ./rcon.sh '/c rcon.print(serpent.block(storage))'  — inspect table
#   ./rcon.sh '/c log("hello")'                  — write to factorio-current.log

set -euo pipefail

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FACTORIO_BIN="$(realpath "$SCRIPT_DIR/../../bin/x64/factorio")"
MODS_DEV_DIR="$(realpath "$SCRIPT_DIR/..")"   # mods_dev/ (parent of this repo)

VERSION=$(jq -r .version "$SCRIPT_DIR/info.json")
MOD_NAME=$(jq -r .name   "$SCRIPT_DIR/info.json")
VERSIONED_NAME="${MOD_NAME}_${VERSION}"

DEBUG_DIR="$SCRIPT_DIR/.debug"
MODS_DIR="$DEBUG_DIR/mods"
SAVES_DIR="$DEBUG_DIR/saves"
CONFIG_DIR="$DEBUG_DIR/config"
SAVE_FILE="$SAVES_DIR/debug-save.zip"
CONSOLE_LOG="$DEBUG_DIR/console.log"
GAME_LOG="$DEBUG_DIR/factorio-current.log"
SCRIPT_OUTPUT="$DEBUG_DIR/script-output"

RCON_PORT=27015
RCON_PASS="factorio-debug"

# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------
case "${1:-}" in
  log)
    echo "Tailing game log: $GAME_LOG"
    exec tail -f "$GAME_LOG"
    ;;
  console)
    echo "Tailing console log: $CONSOLE_LOG"
    exec tail -f "$CONSOLE_LOG"
    ;;
  reset)
    echo "Deleting save: $SAVE_FILE"
    rm -f "$SAVE_FILE"
    echo "Done. Run ./debug.sh to recreate and start."
    exit 0
    ;;
  gui)
    # Launch with full GUI (singleplayer, no headless)
    shift
    exec "$FACTORIO_BIN" \
      --config "$CONFIG_DIR/config.ini" \
      --mod-directory "$MODS_DIR" \
      --load-game "$SAVE_FILE" \
      "$@"
    ;;
esac

# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------
echo "=== Factorio Debug Launcher ==="
echo "Binary : $FACTORIO_BIN"
echo "Mod    : $VERSIONED_NAME"
echo "Debug  : $DEBUG_DIR"
echo ""

mkdir -p "$MODS_DIR" "$SAVES_DIR" "$CONFIG_DIR" "$SCRIPT_OUTPUT"

# Symlink the live mod source into the debug mods dir (versioned name required)
if [ ! -L "$MODS_DIR/$VERSIONED_NAME" ]; then
  ln -sfn "$SCRIPT_DIR" "$MODS_DIR/$VERSIONED_NAME"
  echo "Symlinked mod: $MODS_DIR/$VERSIONED_NAME -> $SCRIPT_DIR"
fi

# Always refresh the symlink target in case version changed
ln -sfn "$SCRIPT_DIR" "$MODS_DIR/$VERSIONED_NAME"

# Copy mod-list.json from mods_dev (enables creative-mod, disables others)
cp "$MODS_DEV_DIR/mod-list.json" "$MODS_DIR/mod-list.json"

# Copy mod-settings.dat if present
if [ -f "$MODS_DEV_DIR/mod-settings.dat" ]; then
  cp "$MODS_DEV_DIR/mod-settings.dat" "$MODS_DIR/mod-settings.dat"
fi

# Write a minimal config.ini pointing write-data at .debug/
cat > "$CONFIG_DIR/config.ini" << EOF
; Factorio debug config — generated by debug.sh
; https://wiki.factorio.com/Factorio_wiki
[path]
read-data=__PATH__executable__/../../data
write-data=$DEBUG_DIR
EOF

# ---------------------------------------------------------------------------
# Create save if missing
# ---------------------------------------------------------------------------
if [ ! -f "$SAVE_FILE" ]; then
  echo "Creating new debug save..."
  "$FACTORIO_BIN" \
    --config "$CONFIG_DIR/config.ini" \
    --mod-directory "$MODS_DIR" \
    --create "$SAVE_FILE" \
    --disable-audio \
    2>&1 | tee -a "$GAME_LOG"
  echo "Save created: $SAVE_FILE"
fi

# ---------------------------------------------------------------------------
# Start headless server
# ---------------------------------------------------------------------------
echo ""
echo "Starting headless server..."
echo "  RCON port    : $RCON_PORT"
echo "  RCON password: $RCON_PASS"
echo "  Game log     : $GAME_LOG"
echo "  Console log  : $CONSOLE_LOG"
echo "  Script output: $SCRIPT_OUTPUT"
echo ""
echo "Output channels:"
echo "  rcon.print(v)         — value echoed back to rcon.sh  ← best for inspection"
echo "  log(\"msg\")           — goes to factorio-current.log"
echo "  helpers.write_file(f, data)  — goes to .debug/script-output/ (Factorio 2.0)"
echo ""
echo "Quick commands:"
echo "  ./rcon.sh '/c rcon.print(game.tick)'             — inspect a value"
echo "  ./rcon.sh '/c rcon.print(serpent.block(storage))'— pretty-print global table"
echo "  ./rcon.sh '/c log(\"hello\")'                     — write to game log"
echo "  ./debug.sh log                                   — tail the game log"
echo "  ./rcon-shell.sh                                  — interactive REPL"
echo ""

exec "$FACTORIO_BIN" \
  --config "$CONFIG_DIR/config.ini" \
  --mod-directory "$MODS_DIR" \
  --start-server "$SAVE_FILE" \
  --rcon-port "$RCON_PORT" \
  --rcon-password "$RCON_PASS" \
  --console-log "$CONSOLE_LOG" \
  --disable-audio
